
// This file has been generated by the GUI designer. Do not modify.
namespace PasswordUsher
{
	public partial class AddProviderWindow
	{
		private global::Gtk.Fixed fixed3;
		private global::Gtk.Label LabelProvider;
		private global::Gtk.Button ButtonSaveProvider;
		private global::Gtk.Entry EntryProvider;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PasswordUsher.AddProviderWindow
			this.Name = "PasswordUsher.AddProviderWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Add Provider");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child PasswordUsher.AddProviderWindow.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.LabelProvider = new global::Gtk.Label ();
			this.LabelProvider.Name = "LabelProvider";
			this.LabelProvider.LabelProp = global::Mono.Unix.Catalog.GetString ("Provider:");
			this.fixed3.Add (this.LabelProvider);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.LabelProvider]));
			w1.X = 49;
			w1.Y = 26;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.ButtonSaveProvider = new global::Gtk.Button ();
			this.ButtonSaveProvider.Sensitive = false;
			this.ButtonSaveProvider.CanFocus = true;
			this.ButtonSaveProvider.Name = "ButtonSaveProvider";
			this.ButtonSaveProvider.UseUnderline = true;
			this.ButtonSaveProvider.Label = global::Mono.Unix.Catalog.GetString ("Save Provider");
			this.fixed3.Add (this.ButtonSaveProvider);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.ButtonSaveProvider]));
			w2.X = 134;
			w2.Y = 84;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.EntryProvider = new global::Gtk.Entry ();
			this.EntryProvider.WidthRequest = 200;
			this.EntryProvider.CanFocus = true;
			this.EntryProvider.Name = "EntryProvider";
			this.EntryProvider.IsEditable = true;
			this.EntryProvider.InvisibleChar = '•';
			this.fixed3.Add (this.EntryProvider);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.EntryProvider]));
			w3.X = 119;
			w3.Y = 23;
			this.Add (this.fixed3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 374;
			this.DefaultHeight = 173;
			this.Show ();
			this.ButtonSaveProvider.Clicked += new global::System.EventHandler (this.SaveProvider);
			this.EntryProvider.Changed += new global::System.EventHandler (this.EnableSave);
		}
	}
}
